//! Generated reference docs. They are committed, and `--check` fails when they drift
//! from the binary (`docs/09-site-and-docs.md` §6).

use std::fs;
use std::path::Path;

use anyhow::{Context, Result, bail};
use clap::CommandFactory as _;
use clap::error::ErrorKind;

/// Where the CLI reference lives until the site exists (`docs/09-site-and-docs.md` §9).
const CLI_REFERENCE: &str = "site/src/generated/cli.md";

/// Writes the CLI reference, or with `check` fails if the committed one is stale.
pub(crate) fn run(root: &Path, check: bool) -> Result<()> {
    let path = root.join(CLI_REFERENCE);
    let fresh = cli_reference()?;
    if check {
        let committed =
            fs::read_to_string(&path).with_context(|| format!("could not read {CLI_REFERENCE}"))?;
        if committed != fresh {
            bail!("{CLI_REFERENCE} is out of date; run `cargo xtask gen-docs`");
        }
        return Ok(());
    }
    if let Some(dir) = path.parent() {
        fs::create_dir_all(dir).with_context(|| format!("could not create {}", dir.display()))?;
    }
    fs::write(&path, fresh).with_context(|| format!("could not write {CLI_REFERENCE}"))
}

fn cli_reference() -> Result<String> {
    Ok(format!(
        "<!-- Generated by `cargo xtask gen-docs` from the clap definition. Do not edit. -->\n\
         \n\
         # CLI reference\n\
         \n\
         ## `kipple --help`\n\
         \n\
         ```text\n\
         {}\n\
         ```\n\
         \n\
         ## `kipple --version`\n\
         \n\
         ```text\n\
         {}\n\
         ```\n",
        printed(&["kipple", "--help"])?.trim_end(),
        printed(&["kipple", "--version"])?.trim_end(),
    ))
}

/// What `kipple` prints for `args`, rendered by clap exactly as the binary would.
fn printed(args: &[&str]) -> Result<String> {
    let Err(error) = kipple::Cli::command().try_get_matches_from(args) else {
        bail!("`{}` printed nothing", args.join(" "));
    };
    if !matches!(
        error.kind(),
        ErrorKind::DisplayHelp | ErrorKind::DisplayVersion
    ) {
        bail!("`{}` failed: {error}", args.join(" "));
    }
    Ok(error.render().to_string())
}
