[package]
name = "kipple-core"
description = "kipple's domain model, policy and engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
crossbeam-channel.workspace = true
thiserror.workspace = true

[lints]
workspace = true
